{
  parserClass="com.tttsaurus.ksml.grammar.KsmlParser"
  psiPackage="com.tttsaurus.ksml.grammar.psi"
  psiImplPackage="com.tttsaurus.ksml.grammar.psi.impl"
  elementTypeHolderClass="com.tttsaurus.ksml.grammar.psi.KsmlTypes"

  tokens = [
    AT='@'

    MODULE='module'
    REQUIRES='requires'
    EXPORT='export'
    GL_VERSION='gl_version'
    GL_REQUIRES='gl_requires'
    FEATURE='feature'

    IDENTIFIER='regexp:[A-Za-z_][A-Za-z_0-9]*'
    NUMBER='regexp:[0-9]+'

    WHITE_SPACE='regexp:[ \t\r\n]+'
    COMMENT='regexp://[^\n]*|/\*([^*]|\*+[^*/])*\*+/'

    GLSL_SYMBOL='regexp:[{}();,=.+\-*/]'
  ]
}

file ::= item*

item ::= ksml_annotation | any_chunk

any_chunk ::= IDENTIFIER | NUMBER | GLSL_SYMBOL

ksml_annotation ::= module_decl
                  | requires_decl
                  | gl_version_decl
                  | gl_requires_decl
                  | export_decl
                  | feature_decl



module_decl ::= AT MODULE IDENTIFIER {pin=1}

requires_decl ::= AT REQUIRES IDENTIFIER {pin=1}

gl_version_decl ::= AT GL_VERSION NUMBER {pin=1}

gl_requires_decl ::= AT GL_REQUIRES NUMBER {pin=1}

feature_decl ::= AT FEATURE IDENTIFIER {pin=1}

export_decl ::= AT EXPORT IDENTIFIER? {pin=1}
